design:
  input_space:
    - _target_: f3dasm.ContinuousParameter
      name: vol_req
      lower_bound: 0.1
      upper_bound: 0.5
    - _target_: f3dasm.ContinuousParameter
      name: radius_mu
      lower_bound: 0.001
      upper_bound: 0.005
  output_space:
    - _target_: f3dasm.ContinuousParameter
      name: status

material:
  _target_: f3dasm_simulate.abaqus.material.CompositeMaterial
  matrix_material:
    _target_: f3dasm_simulate.abaqus.material.ElasticMaterial
    youngs_modulus: 1.0
    poisson_ratio: 0.3
  fiber_material:
    _target_: f3dasm_simulate.abaqus.material.PlasticMaterial
    youngs_modulus: 100.0
    poisson_ratio: 0.3
    hardening_law:
      _target_: f3dasm_simulate.abaqus.material.LinearHardeningLaw
      a: 0.5
      yield_stress: 0.5

microstructure:
  _target_: f3dasm_simulate.abaqus.microstructure.CircleMicrostructure
  size: 0.048
  radius_mu:
  radius_std: 0.0
  vol_req:
  seed: 42

loading:
  # _target_: f3dasm_simulate.abaqus.loading.RegularLoading
  # strain: [0.02, 0.02, 0.02]
  _target_: f3dasm_simulate.abaqus.loading.PathLoading
  strain: [0.02, 0.02, 0.02]
  amplitude_generator:
    _target_: f3dasm_simulate.abaqus.loading.AmplitudeGenerator
    num_control: 8
    num_steps: 100
    num_amplitude: 1
    arg_name: amplitude
    interpolation_method: quadratic
    num_dim: 3
    seed: 42

abaqus:
  platform: "ubuntu"
  num_cpu: 1
  print_info: False
  simulation_time: 1.0
  mesh_partition: 50
  num_steps: 100
  job_name: "job"

files:
  main_work_directory: "."
  script_path: /home/martin/Documents/GitHub/f3dasm_simulate/src/f3dasm_simulate/abaqus/scriptbase
  current_work_directory: case_0
  post_path: basic_analysis_scripts.post_process
  post_script: PostProcess2D

hpc:
  jobid: -1
  jobqueue_filename: "jobqueue"

experimentdata:
  existing_data_path: False
  name: "cddm_abaqus"
  sampler: RandomUniform
  seed: 1
  number_of_samples: 3
